### PR TITLE
Feature/rename classes

### PR DESCRIPTION
**Pull request by Baachi**
I just renamed all classes to follow the "new" coding guideline from TYPO3.
So all classes now located under the `Classes` directory and sometimes I renamed them, so their names are more descriptive. 

I'm unsure if the ClassAliasMap is loaded in the non-composer mode. If not it shouldn't be a big deal, but I need to add some little code to make it work. 

I also stumble upon some issues in the code, sometimes I could fix them but someone needs to recheck this. 

What to do:
 - [x] Unit Tests pass
 - [x] Replace deprecated classes
 - [ ] Add more unit tests
 - [x] Add class alias map to composer.json
 - [x] Check if class alias map are available for non composer installations

### CODE REVIEW

**Comment by rengaw83** [comment]
The class alias map loader, which loads the `Migrations/Code/ClassAliasMap.php` file, exists since TYPO3 7 and should works in noncomposer mode. 
We should add this to `composer.json`:
```json
{
    "extra": {
        "typo3/class-alias-loader": {
            "class-alias-maps": [
                "Migrations/Code/ClassAliasMap.php"
            ]
        }
    }
}
```

For IDE's we should add a `Migrations/Code/LegacyClassesForIde.php` File with some `oldclass extends namespace` stuff in it, like this:
```php
/**	
 * @deprecated since 9.6, removed since 11.0	
 */	
class tx_mktools_model_Pages extends \DMK\Mktools\Model\Page {}
```

**Comment by Baachi** [comment]
@rengaw83 Thanks for the explanation! I added these two files/changes and a little PHP script which generates this file. But I'm not sure how to deal with final classes. Theoretically this shouldn't be the problem, because the PHP compiler will never use this file but my IDE mark this file as invalid because I extend from a final class.

Any thoughts about that?

**Comment by rengaw83** [comment]
Final and static utility classes are a generally problem. 

I do not have an idea for final classes, apart from copying those (doublicated code).

These static util classe are a problem too. When i use `tx_mktools_util_miscTools:isSeoRobotsMetaTagActive` in my ext, it should continue to work. Does it with just the ClassAliasMap file? Dont think so. A LegacyStaticClasses File should be loaded too, or?

**Comment by Baachi** [comment]
> These static util classe are a problem too. When i use tx_mktools_util_miscTools:isSeoRobotsMetaTagActive in my ext, it should continue to work. Does it with just the ClassAliasMap file?

I don't see here any problem, the call `tx_mktools_util_miscTools:isSeoRobotsMetaTagActive` would call the composer autoloader, to load the class `tx_mktools_util_miscTools`. The composer alias loader from TYPO3 hooks in and renamed the class and loads the new class instead. 

Copy the code just for the autocompletion, looks not worth for me. Remove the final keyword looks not worth for me either. 

Maybe we could use the `.phpstorm.meta.php` file, but this is out of the scope of this issue. Apart from that, we could also leave it as it is, because this file will never be executed and won't throw an exception or parse error. Only your IDE will inform you, that something is wrong, but the autocompletion will still work. 

@hbochmann Do you see any other options?

**Comment by rengaw83** [comment]
When just the IDE means that final classes are wrong and the code still works as expected (have not testet it yet), than i dont know why we should add workarounds to tell the ide that it is ok.  
If it bothers you, you should use the new namespace ;)

A last thing we can do: adding phpdoc to the LegacyClassesForIde to say the ide that these old classes are deprecated:
```php
/**	
 * @deprecated since 9.6, removed since 11.0	
 */
```

**Review by rengaw83 — CHANGES_REQUESTED** [review]
I have tried to install this branch in a noncomposer typo3 environment. But the install fails with a errors:
```
Uncaught TYPO3 Exception: 
Class 'DMK\Mktools\Utility\tx_rnbase_configurations' not found
Error thrown in typo3conf/ext/mktools/Classes/Utility/Misc.php in line 48.
```

After fixing that I could install it. 

Wish we had phpstan or something like that allready.
There are many other places we has to fix first.

**Review by rengaw83 — APPROVED** [review]
Now it looks good for me :+1: 

@hannesbochmann do you have any objections or an idea for the extend final class errors in ide?

**Comment by hannesbochmann** [comment]
Regarding the problem with final classes in the IDE: I wouldn't put any effort into it and leave it as it is. I see no other options and wouldn't vote for removing the final keyword. A benefit is that a developer is forced to replace the occurrences of old final classes if he doesn't want an IDE overloaded with errors.
Furthermore adding @deprecated in the class map for the IDE is a good idea.

**Review by hannesbochmann — APPROVED** [review]

**Comment by rengaw83** [comment]
Was merged with 98d4cb20d9e7e440d21771e10e0aaa09b09ca313 into the new branch https://github.com/DMKEBUSINESSGMBH/typo3-mktools/tree/10.4.

**Pull request closed without merging**
